name: utrgv_campus_connect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3
  provider: ^6.1.5+1
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.1
  animations: ^2.1.0
  form_field_validator: ^1.1.0
  fluttertoast: ^9.0.0
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  search_page: ^2.3.0
  http: ^1.5.0
  intl: ^0.20.2
  uuid: ^4.5.1
  google_mlkit_face_detection: ^0.13.1
  shared_preferences: ^2.2.2   # ✅ FIXED — this is the correct one!

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
